### DISCUSSION TITLE
Examples generated for array fields are wrong

### DISCUSSION THREAD

**Discussion by yurisasuke** [swaggest/openapi-go#104] [Q&A] [answered]
I have this struct:
```
type ADefinition struct {
	Versions             []string                `json:"versions"  example:"[\"Default\",\"v1\"]"
 }
```
 
 which produce the following OAS:
 

     
  ```
versions:
          items:
            example: '["Default","v1"]'
            type: string
          nullable: true
          type: array
```

but what I expect it to produce is:

 ```
       versions:
          items:
            type: string
          nullable: true
          type: array
          example: ["Default", "v1"]
```

Am i doing something wrong or is this a bug ?  Or how can I add an example for an array instead of array items ?(This happens for all slices where the example produced  is  in the array item level instead of being on the array level). I have also tried to use Examples tag put that doesn't work either.
