### DISCUSSION TITLE
How do I get the value for a parameter example?

### DISCUSSION THREAD

**Discussion by mcred** [swaggest/openapi-go#61] [Q&A] [answered]
In the following spec there is an example value:
```yaml
  '/workflows/{workflowId}':
    parameters:
      - name: workflowId
        description: The unique identifier for the Workflow
        in: path
        required: true
        schema:
          type: integer
          minimum: 1
        example: 1
```
What is the proper way to get the value from the Example interface?
<img width="622" alt="Screenshot 2023-03-08 at 1 23 26 PM" src="https://user-images.githubusercontent.com/4326032/223800663-8a0f525b-e434-462e-bcd1-8bdbfc39a89a.png">
