### DISCUSSION TITLE
How to add form field in query?

### DISCUSSION THREAD

**Discussion by kpoznyakov** [swaggest/openapi-go#66] [Q&A]
I would like to add something like custom fields with filters, if i made id myself, i made it like
```
      - description: long desc for all filters
        in: query
        name: filters
        schema:
          type: object
          description: another one desc
          example: {"filter1:foo:bar": "baz", "filter2:rick:mortн": 42}
          additionalProperties:
            type: string
        style: form
        explode: true  
```
how do i can done this with openapi-go?
