### DISCUSSION TITLE
How to generate nullable struct references?

### DISCUSSION THREAD

**Discussion by benjamin-ratier** [swaggest/openapi-go#78] [Q&A] [answered]
Hello,

I want to be able to make a struct nullable:

```go
type Bar struct {
   Foo *FooStruct `json:"foo"`
}
```

I’m using [kin-openapi](https://github.com/getkin/kin-openapi), to validate my http calls against my generated OpenAPI file, and for a struct to be optional in my http response, I need:

```yaml
...
  - foo:
    - nullable: true 
    - allOf:
      - $ref: '#components/schemas/foostruct'
...
```

I was able to move the generated `$ref` into `allOf` with `reflector.DefaultOptions` and `InterceptNullability` (or `InterceptProperty`), but I don't see how to set `nullable` in the `jsonschema.Schema` object and propagate it in `openapi3.schema` object.

Would you have any suggestions ?

Thanks a lot in advance !
