### ISSUE TITLE
The OAS definition produced for []bytes seems to be wrong

### ISSUE THREAD

**Issue by Keithwachira** [swaggest/openapi-go#111]
**Describe the bug**
If you have []bytes as one of your field in the OAS it is represented as an array 

At the moment as a work arounf I am using  PrepareJSONSchema to change the generated output. 

Sample  struct

```
type Asset struct {
	DBID        ObjectId  `bson:"_id,omitempty" json:"_id,omitempty" gorm:"primaryKey;column:_id" example:"664c9b735715ec3f798bbcd2"`
	ID          string    `bson:"id" json:"id" example:"my-unique-template-id"`
	Data        []byte    `bson:"data" json:"data"`
	
}

```
What is produced in the OAS:
  ```
  Asset:
      properties:
        _id:
          example: 664c9b735715ec3f798bbcd2
          type: string
        data:
          items:
            minimum: 0
            type: integer
          nullable: true
          type: array
```

**Expected behavior**
I would expect it to have produced a string with binary format like below:
```
data:
         type: string
         format: byte
```
