### ISSUE TITLE
integer types missing format

### ISSUE THREAD

**Issue by RPGillespie6** [swaggest/openapi-go#133]
Take the following snippet:

```
oc, err = reflector.NewOperationContext("GET", "/api/internal/dicom-data-lake/patients")
// ...
type path1 struct {
    ID int64 `path:"id"`
}
oc.AddReqStructure(new(path1))
```

In this case, the resulting YAML is:
```
parameters:
- in: path
  name: id
  required: true
  schema:
    type: integer
```

However, the fact that it was a 64 bit integer was lost. Should be:
```
parameters:
- in: path
  name: id
  required: true
  schema:
    type: integer
    format: int64
```

See: https://spec.openapis.org/oas/v3.1.0.html#data-types
