### ISSUE TITLE
Pointer primitives does not end up nullable

### ISSUE THREAD

**Issue by xobotyi** [swaggest/openapi-go#43]
```go
type Req struct {
	Sector   *int   `query:"sector"`
}
```

Generates to
```yaml
      parameters:
      - in: query
        name: sector
        schema:
          type: integer
```

I've expected pointer fields to be described as nullable
