### ISSUE TITLE
Set response and request schemas without declared structure?

### ISSUE THREAD

**Issue by aosderzhikov** [swaggest/openapi-go#96]
Hi, very nice lib!

My app knows about response format only during runtime(it takes it from config file). So I cant declare response format with struct. 
Here is any way how I can set response schema with json, yaml, map or something else? 

```
getOp, _ := reflector.NewOperationContext(http.MethodGet, "/user/{id}")
getOp.AddReqStructure(new(struct {
	ID string `path:"id"`
}))

getOp.AddRespStructure()  // <- put json, yaml, map or something else here
```

**Comment by vearutop** [comment]
Please check if [virtual structure](https://github.com/swaggest/jsonschema-go#virtual-structure) works for your case.

**Comment by aosderzhikov** [comment]
Thanks, I found this useful! There is a way to add response structure with raw yaml or json?

Like: 
```
getOp.AddRespStructure(`
response:
  type: object
  properties:
    field1:
      type: string
    field2:
      type: integer
.....`) 
```
